## routes.yaml

routes:
  /archive/:
    controller: channel
    template: archive
    # data: page.archive
  /signup/:
    template: signup
    # data: page.singup
  /signin/:
    template: signin
    # data: page.signin
  /membership/:
    template: membership
    # data: page.membership
  /tags/:
    template: tags
    # data: page.tags

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/